### ISSUE TITLE
사용할 ui 테마를 정했으면 좋겠습니다.

### ISSUE THREAD

**Issue by comfuture** [comfuture/vuetiful-meetup#2]
이 기회에 element-ui를 만져볼 생각을 했는데, 시도해보니 용량이 비교적 크고 (vendor 에 무려 900KB가 증가),
firebase에서 사용 가능한 마지막 버전인 nuxt-1.0.0-rc11 에서는 의도대로 동작하지 않는 부분이 있어 보입니다.

**Comment by ChangJoo-Park** [comment]
빠르게 작업하려면 어떤게 좋을까요

bootstrap이라던가.. bootstrap이라던가.. bootstrap.................

@comfuture 취향이 궁금합니다

**Comment by comfuture** [comment]
@ChangJoo-Park 제 취향은 sem 중요하지 semant 않습 semanti 니다.
feature에 나열된 ui를 수용하면서 가벼운것이면 좋겠네요

**Comment by ChangJoo-Park** [comment]
s...e...semantic ui를 써볼 수 있는 좋은 기회겠군요

시맨틱 ui의 [card ui](https://semantic-ui.com/views/card.html) 가 적절하게 사용할 수 있겠네요

**Comment by comfuture** [comment]
semantic ui 결정
