### ISSUE TITLE
라우트는 어떻게 해야할까요?

### ISSUE THREAD

**Issue by ChangJoo-Park** [comfuture/vuetiful-meetup#3]
```
### For attendee
- [ ] 밋업 일정 및 정보
- [ ] 밋업 등록 정보 조회
- [ ] 이메일로 로그인
- [ ] 문자 인증번호로 로그인

### For staff
- [ ] 참가자 목록 열람
- [ ] 참가자 목록 검색
- [ ] 참가자 체크인
  * [ ] 매뉴얼 체크인
  * [ ] 바코드로 체크인

### For organizer
- [ ] 밋업 생성
- [ ] 참가자 목록 벌크 업로드
```

README에 있는 내용 가져왔습니다

페이지가 꼭 필요한 부분
- 메인페이지
- 등록 정보 조회 페이지 (for attendee)
- 참가자 목록 리스트 (여기에 검색을 포함할 수도 있어 일단 제외합니다)
- 참가자 체크인 페이지 (참가자 상세 내역으로 사용할 수 있을 것 같습니다)
- 밋업 관리 페이지 (+ 기타등등..)

이 정도 고민해봤는데 로그인같은 경우에는 모달로 대체할 수 있을 것 같아서 제외했습니다.

**Comment by comfuture** [comment]
지금부터 정하면 되는거 같습니다.
제안해봅니다.

- `/` 메인페이지
- `/me/meetup` 등록 정보 조회 페이지 (for attendee)
- `/meetup/:meetup/attendee` 참가자 목록 리스트 (여기에 검색을 포함할 수도 있어 일단 제외합니다)
- `/me/meetup/:meetup` 참가자 체크인 페이지 (참가자 상세 내역으로 사용할 수 있을 것 같습니다)
- `/organize/...` 밋업 관리 페이지 (+ 기타등등..)

**Comment by comfuture** [comment]
최소한의 route만 사용하는것으로 우선 구현
