### ISSUE TITLE
setup:firebase script 파일 없음 오류

### ISSUE THREAD

**Issue by ChangJoo-Park** [comfuture/vuetiful-meetup#6]
`mv .setup-firebaserc .firebaserc` 이렇게 되어있는데 실제로 프로젝트에는 `.setup-firebaserc` 파일이 없습니다

`.firebaserc`를 숨기기 위함으로 보이는데 맞을까요?

https://github.com/davidroyer/nuxt-ssr-firebase

이 프로젝트와 유사한 구조라면 `.firebaserc` 를 `.gitignore` 에 추가하고 
안내를 위한 `.setup-firebaserc` 를 만들면 될 것같습니다

PR 올리면 리뷰 부탁드려요

**Comment by comfuture** [comment]
지적해주신 nuxt-ssr-firebase 저장소로부터 수정한 소스가 맞습니다.
다만, .firebaserc 파일이 없으면 처음부터 동작시험을 해볼 수 없으므로 이번 프로젝트에서는 기본 설정을 다 넣어 커밋하려고 했습니다. 
수정해주신 PR 대신 package.json 의 setup 스크립트를 수정하는 방향으로 반영하는 것이 어떨까요?

**Comment by ChangJoo-Park** [comment]
아 그럴수도 있겠네요 
로컬에서 개발할때는 스스로 파이어베이스 프로젝트를 만들고 거기서 테스트를 하는게 낫지 않을까 라는 생각에서 작업했어요 
제가 올린PR은 닫아도 될거같습니다

**Comment by comfuture** [comment]
컨트리뷰터 님들께는 제 firebase project도 공유할 예정입니다.
이해해주셔서 감사합니다.

**Comment by comfuture** [comment]
보일러플레이트가 아니므로 해당 이슈 보류
